- name: install sshd
  ansible.builtin.package:
    name:
    - openssh-server
    state: present

- name: update sshd service enabled/started
  ansible.builtin.systemd:
    name: sshd
    enabled: yes
    state: started

- name: modify sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    backup: yes
    validate: sshd -t -f %s
    regexp: "{{ item.pattern }}"
    line: "{{ item.replace }}"
  loop:
    - pattern: '^#?\s*PermitRootLogin'
      replace: 'PermitRootLogin no'
    - pattern: '^#PermitEmptyPasswords'
      replace: 'PermitEmptyPasswords no'
    - pattern: '^#AuthorizedKeysCommandUser'
      replace: 'AuthorizedKeysCommandUser root'
    - pattern: '^#AuthorizedKeysCommand'
      replace: 'AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys'
  notify:
    - update sshd service restarted
